### PR TITLE
QSTiles: Add Android Q Beta 4 QS styles [3/3]

### PR DESCRIPTION
**Pull request by Zaviyar786**

### CODE REVIEW

**Review by phenomenall — COMMENTED** [review]
Pls do check the folder path in stag ..wr we picked the qs styles

**Comment by Zaviyar786** [comment]
ok sir..noted

**Comment by vjspranav** [comment]
@HeartStealer786 Testing bot

**Comment by phenomenall** [comment]
@vjspranav Kya kahana cha rahe ho😂😂

**Comment by DrtSinX98** [comment]
@phenomenall .

**Pull request closed without merging**
